version: '3'
services:
  user-service:
    image: user-service.jar
    ports:
        - "9096:8081"
    networks:
      - my_network
    depends_on:
      - service-registry
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/

  beneficiary-service:
    image: beneficiary-service.jar
    ports:
      - "9090:8083"
    networks:
      - my_network
    depends_on:
      - service-registry
    environment:
      - SPRING_APPLICATION_NAME=beneficiary-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/

  notification-service:
    image: notification-service.jar
    ports:
      - "9093:9092"
    networks:
      - my_network
    depends_on:
      - service-registry
    environment:
      - SPRING_APPLICATION_NAME=notification-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/

  api-gateway:
    image: api-gateway.jar
    ports:
      - "9094:8080"
    networks:
      - my_network
    depends_on:
      - service-registry
    environment:
      - SPRING_APPLICATION_NAME=api-gateway
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/

  service-registry:
    image: service-registry.jar
    ports:
      - "9091:8761"
    networks:
      - my_network
    environment:
      - SPRING_APPLICATION_NAME=service-registry

networks:
  my_network:
