server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    config:
      enabled: false  # Assuming you don't have a config server setup for this service
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/