# Server settings
server:
  port: 8082


# Database configuration
spring:
  application:
    name: Dummy-Service
  datasource:
    url: jdbc:mysql://localhost:3306/student-service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  config:
#    import: configserver:http://localhost:8085
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
#    eureka:
#      client:
#        service-url:
#          defaultZone: http://localhost:8761/eureka